name: Create tags and release

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  release:
    name: Create a Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create a Release
        uses: List-KR/semver-release@2.2.0