name: Capture remote tokens

on:
  workflow_dispatch:
  schedule:
    - cron: '0/10 * * * *'

jobs:
  capture:
    name: Capture remote tokens
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        location: [ar, de, fr, gb, hk, jp, kr, us, au, ro, se, sg, uk]
        referer: [dogdrip.net]
        domain: [css-load.com]
        useragent: ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36", "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36", "Mozilla/5.0 (Linux; Android 13; SM-G981B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36", "Mozilla/5.0 (iPhone; CPU iPhone OS 17_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Mobile/15E148 Safari/604.1"]
    steps:
      - name: Setup snap
        run: |
          sudo apt update
          sudo apt install snapd
      - name: Setup proxy
        run: |
          sudo snap install hola-proxy
          (exec hola-proxy -proxy-type direct -country ${{ matrix.location }} &> /dev/null &)
          sleep 10
      - name: Set up NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download the script content
        run: |
          curl -x http://127.0.0.1:8080 -A "${{ matrix.useragent }}" --referer "https://${{ matrix.referer }}" https://${{ matrix.domain }}/loader.min.js > /tmp/target.js
      - name: Capture remote tokens
        uses: List-KR/microShield-token-gen@1.0.2
        with:
          target: '/tmp/target.js'
  release:
    name: Create a Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Pull the latest changes
        run: |
          git pull
      - name: Create a Release
        uses: List-KR/semver-release@2.2.0
    needs: [capture]