name: Capture remote tokens

on:
  workflow_dispatch:
  schedule:
    - cron: '0/5 * * * *'

jobs:
  capture:
    name: Capture remote tokens
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        location: [ar, de, fr, gb, hk, jp, kr, us, au]
        referer: [dogdrip.net]
        domain: [css-load.com]
    steps:
      - name: Setup proxy
        run: |
          docker run -d -p 127.0.0.1:8080:8080 yarmak/hola-proxy -proxy-type direct -country ${{ matrix.location }}
          sleep 10
      - name: Set up NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download the script content
        run: |
          curl -x http://127.0.0.1:8080 --referer "https://${{ matrix.referer }}" https://${{ matrix.domain }}/loader.min.js > /tmp/target.js
      - name: Capture remote tokens
        uses: List-KR/microShield-token-gen@1.0.2
        with:
          target: '/tmp/target.js'
  release:
    name: Create a Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Pull the latest changes
        run: |
          git pull
      - name: Create a Release
        uses: List-KR/semver-release@2.2.0
    needs: [capture]