name: Capture remote tokens

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  release:
    name: Create a Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Capture remote tokens
        uses: List-KR/microShield-token-gen@1.0.0
        with:
          config: 'config.json'